postgres:
  image: postgres:9.5
  environment:
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=postgres
  volumes:
   - ./docker/postgres_config:/docker-entrypoint-initdb.d
  ports:
   - "5432:5432"
